# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict   # checks for files that contain merge conflict strings.
      - id: debug-statements  # checks for debugger imports and py37+ `breakpoint()` calls in python source.

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.1'  # add version here
    hooks:
      - id: poetry-check

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.6
    hooks:
      # Run the linter.
      - id: ruff

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
    - id: bandit
      args: [ "-c", "pyproject.toml", "-r", "." ]
      additional_dependencies: [".[toml]"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--fix"]  # Automatically fix basic issues

  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Type Check
        entry: bunx vue-tsc
        args: [--noEmit, --skipLibCheck, -p, tsconfig.app.json]
        language: system
        files: \.(ts|vue)$
        exclude: ^(node_modules|\.venv|venv|\.pytest_cache|__pycache__|\.ruff_cache)/
        pass_filenames: false
      - id: bun-lint
        name: Bun Lint
        entry: bun lint
        language: system
        files: \.(js|ts|vue)$
        exclude: ^(node_modules|\.venv|venv|\.pytest_cache|__pycache__|\.ruff_cache)/
        pass_filenames: false
